pipeline:
  agent:
    label: any

  environment:
    CI: "true"  # Переменная окружения CI, строка

  stages:
    - stage: Checkout Code
      steps:
        - checkout scm  # Используем стандартное описание для клонирования репозитория

    - stage: Install Dependencies
      steps:
        - sh: 'npm ci'  # Устанавливаем зависимости с использованием npm

    - stage: Install Playwright Browsers
      steps:
        - sh: 'npx playwright install'  # Устанавливаем необходимые браузеры для Playwright

    - stage: Run Playwright Tests
      steps:
        - sh: 'npx playwright test'  # Запускаем тесты с использованием Playwright

    - stage: Archive Report
      steps:
        - sh: 'zip -r playwright-report.zip playwright-report || true'  # Архивируем отчёт
        - archiveArtifacts:
            artifacts: 'playwright-report.zip'  # Архивируем файл отчёта
